spring:
  datasource:
    url: jdbc:mysql://localhost:13306/deofis_dev?allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Argentina/Cordoba
    username: root
    password: 1224
    driver-class-name: com.mysql.cj.jdbc.Driver
    initializationMode: always
    platform: mysql
    data: classpath:/data-mysql.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 115b497d81c8f5
    password: f57c78b927010c

endpoints:
  baseUrl: http://localhost:8080
  clientUrl: http://localhost:4200

amazon:
  s3:
    bucketName: deofis-dev-bucket
    endpoint: https://deofis-dev-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: ENC(fH9vySrU4xPEmDqI0m79/RqQRzrnjiOtpVDTokbfEfg=)
    secretKey: ENC(vIxqo/d8mOUnpVDQRJlJrD8XooTw8BFBWAcnnpsix8JfWt/M3p5S7Xn08sl2jG3wQYy5GSy7PsU=)

paypal:
  clientId: AULkwIac0isgBpdaemBxUi7VABSAksciHwhnwbJHh-Och2Kf8qAJ0cwFbYrouVgA5Mqo9fHonoyof3EJ
  clientSecret: EFoADORBnsYEkgM6YNfTU_pfHu0D8Npi2W8ZFASWysDKWnicY0OQX2sYCyCQs8H7RU9w5bnleMcUP5JP

mercadopago:
  publicKey: TEST-d0859391-4a9a-47ec-a0c1-74b6d81f7fa3
  accessKey: TEST-1434091456534127-011920-67ef4409b41a150450c09f1fbac42aae-703836772

magicbell:
  apiKey: fe895cc2053486135913f5557c5fae1ca049a04e
  apiSecret: c7d010e7def46aec61c8524f85371103a1e48fb0

jwt:
  expirationInMillis: 3600000
