spring:
  datasource:
    url: jdbc:h2:mem:deofis_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: eb1eece6b19a9c
    password: ed814f343a2257

  h2:
    console:
      enabled: true

endpoints:
  baseUrl: http://localhost:8080
  clientUrl: http://localhost:4200

amazon:
  s3:
    bucketName: deofis-images-bucket
    endpoint: https://deofis-images-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: ENC(6ik+s8LqW3b68c9K1eOX3yoxpeU6+LgcboZbr07ZANw=)
    secretKey: ENC(RkOXxN4A2LF+JrZGafMYlbNwY6JkcIdyPNv+vjahgcHfg0gTjm4i/fRt9SWM33RN46vY/N/50gg=)

paypal:
  clientId: AULkwIac0isgBpdaemBxUi7VABSAksciHwhnwbJHh-Och2Kf8qAJ0cwFbYrouVgA5Mqo9fHonoyof3EJ
  clientSecret: EFoADORBnsYEkgM6YNfTU_pfHu0D8Npi2W8ZFASWysDKWnicY0OQX2sYCyCQs8H7RU9w5bnleMcUP5JP

mercadopago:
  publicKey: TEST-d0859391-4a9a-47ec-a0c1-74b6d81f7fa3
  accessKey: TEST-1434091456534127-011920-67ef4409b41a150450c09f1fbac42aae-703836772

magicbell:
  apiKey: fe895cc2053486135913f5557c5fae1ca049a04e
  apiSecret: c7d010e7def46aec61c8524f85371103a1e48fb0

jwt:
  expirationInMillis: 3600000
