spring:
  datasource:
    url: jdbc:mysql://deofis-qa.crhfvajzxctv.eu-west-2.rds.amazonaws.com/deofis_qa
    username: user_qa
    password: ENC(2ns5ABYULg5Mg6srSA5tefYRlkqAebbl)
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: deofis.github@gmail.com
    password: ENC(2j2tFEz5rbsf0BcsJH4U5hw9ogYdmL3o)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true

endpoints:
  baseUrl: https://cursos.api.deofisdev.online
  clientUrl: https://wantfrom-tienda.web.app

amazon:
  s3:
    bucketName: deofis-dev-bucket
    endpoint: https://deofis-dev-bucket.s3.eu-west-2.amazonaws.com/
    accessKey: ENC(fH9vySrU4xPEmDqI0m79/RqQRzrnjiOtpVDTokbfEfg=)
    secretKey: ENC(vIxqo/d8mOUnpVDQRJlJrD8XooTw8BFBWAcnnpsix8JfWt/M3p5S7Xn08sl2jG3wQYy5GSy7PsU=)

paypal:
  clientId: AULkwIac0isgBpdaemBxUi7VABSAksciHwhnwbJHh-Och2Kf8qAJ0cwFbYrouVgA5Mqo9fHonoyof3EJ
  clientSecret: EFoADORBnsYEkgM6YNfTU_pfHu0D8Npi2W8ZFASWysDKWnicY0OQX2sYCyCQs8H7RU9w5bnleMcUP5JP

mercadopago:
  publicKey: TEST-d0859391-4a9a-47ec-a0c1-74b6d81f7fa3
  accessKey: TEST-1434091456534127-011920-67ef4409b41a150450c09f1fbac42aae-703836772

magicbell:
  apiKey: fe895cc2053486135913f5557c5fae1ca049a04e
  apiSecret: c7d010e7def46aec61c8524f85371103a1e48fb0

jwt:
  expirationInMillis: 900000

server:
  port: ${PORT:5000}